language: node_js
node_js:
- '4'
before_script:
- npm install grunt-cli -g
deploy:
  provider: npm
  email: dortega@idealista.com
  api_key:
    secure: X6KgmiU/SG+WRDDh04HKRnQnPHqPb4WmYhyGYOPfTKrCa3VeYAvNffkOQGpz8JTfwea92SdOyCLlGUFrmcw3SqzhE7Wu/S7QcifUYkGbIX0z0Hx/QeFwwnQ6p9LTb96ZOJJDhc5JG6318DuHDPbLkLnF5jN+SJnthmwFv6wlkEI67y9BbvX80oS14qCToAwLidldlATB713c0VEvWohX4fxhxoVCZa9exL12oLfPStBeC38IIGyr/oHXv76gWnXkt5cPAx8zW5QUAlN5C2xUKWB17U1r2xA5+APWnkmT2hsNaIe8QLXCgEot7Z7c407BuPEd0WsW5dze3onwAIP9diRzZ7pFt7kADZ8OfoFHyhNxuNJG3oaq0K16x0e0/xRPQnMvSAwwZ1/3uEsMJ+a3M0tl7XrplWk0YkWAfVw+FBZKb5WMVuyORpTwxHGjP+xhcpAzXtNEnbsC+0xenK/pwmKe54907k2g1snW+d+cg8OCmJVMDnOUxf/ACKElaO/vgebbEKMXljZXquFnNKzj2CsQgLV2WPJJXDyj4UdN4sARg3d5gFkoHz8/vB5p1pg3t0UygpoUmKRfKeUnUfeBFJw+jPbTckf/frr5MH1fGTvUAgog0YtpQhu3ZBwcIDi7b9QRrFPrCFJEGcFZmWzvWzNp+IS8FemioqvQAguZvZE=
  on:
    tags: true
    repo: idealista-tech/tlsh-js
